name: pr-check

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk8:latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build test --scan
